apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vote-app
spec:
  hosts:
  - vote-app
  http:
  - route:
    - destination:
        host: vote-app
        subset: v1
      weight: 70
    - destination:
        host: vote-app
        subset: v2
      weight: 30
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: vote-app
spec:
  host: vote-app
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
