apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-canary
  labels:
    app: vote-app
    track: canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
      track: canary
  template:
    metadata:
      labels:
        app: vote-app
        track: canary
    spec:
      containers:
      - name: vote-app
        image: celiaoued/vote-app:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
          limits:
            cpu: "200m"
            memory: "1000Mi"
        env:
        - name: REDIS
          value: "rediscluster"
        - name: STRESS_SECS
          value: "10"
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redispw
              key: password
